TeVeO/TeVeO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('TeVeOapp.urls')),
]

TeVeO/TeVeOapp/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('camaras/', views.camaras, name='mainCameras'),
    path('camaras/json', views.camaras_json, name='cameras_json'),
    path('camaras/<str:id>/', views.pag_camaras, name='camera'),
    path('camaras/<str:id>/comment', views.cargar_comentarios, name='get_comments'),
    path('camaras/<str:id>/dyn', views.camara_id, name='camera_dyn'),
    path('camaras/<str:id>/img', views.get_imagen, name='latest_image'),
    path('camaras/<str:id>/json', views.camara_json, name='camera_json'),
    path('comentario/', views.ver_comentarios, name='comment'),
    path('config/', views.config, name='config'),
    path('config/auth_link', views.token_sesion, name='auth_link'),
    path('config/set_session', views.config_sesion, name='set_session'),
    path('help/', views.help, name='ayuda'),
]

TeVeO/TeVeOapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Camera(models.Model):

    source_id = models.CharField(max_length=100)
    id = models.CharField(max_length=100, primary_key=True)
    src = models.CharField(max_length=200)
    name = models.CharField(max_length=100)
    coordinates = models.CharField(max_length=100)
    img_path = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.source_id}{self.id} - {self.name}'


class Comment(models.Model):

    name = models.CharField(max_length=100)
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    img_path_comment = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.camera} - {self.name} - {self.comment} - {self.date}'


class Token(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=200)
    font_size = models.CharField(max_length=200, null=True)
    font_family = models.CharField(max_length=200, null=True)

    def __str__(self):
        return f'{self.user} - {self.token}'

TeVeO/TeVeOapp/forms.py
# Defines una clase para tu formulario que hereda de forms.Form
from django import forms

class ConfigForm(forms.Form):
    username = forms.CharField(
        label='Nombre de Usuario', max_length=100, required=False)

    font_size = forms.ChoiceField(
        choices=[('large', 'Grande'),
                 ('standard', 'Normal'),
                 ('small', 'Pequeña')])


    font_family = forms.ChoiceField(choices=[
        ('Arial', 'Arial'),
        ('Times New Roman', 'Times New Roman'),
        ('Courier New', 'Courier New'),
    ])

TeVeO/TeVeOapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404

from .models import Camera, Comment, Token
from .forms import ConfigForm
from .camaras import *
from .configuration import *

from django.utils import timezone
import time

from django.contrib import messages
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.models import User
from django.core import serializers
from django.views.decorators.cache import never_cache
from django.urls import reverse

from urllib.parse import urlparse, parse_qs

# Create your views here.
def config(request):
    if request.method == 'POST':
        form = ConfigForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            font_size = form.cleaned_data['font_size']
            font_family = form.cleaned_data['font_family']
            request.session['username'] = username
            request.session['font_size'] = font_size
            request.session['font_family'] = font_family
            user, created = User.objects.get_or_create(username=username)
            if user is not None:
                token, created = Token.objects.get_or_create(user=user)
                if created:
                    token.token = default_token_generator.make_token(user)
                token.font_size = font_size
                token.font_family = font_family
                token.save()
                request.session['auth_token'] = token.token
            return HttpResponseRedirect('/')
        else:
            print(form.errors)
    else:
        form = ConfigForm()

    username, font_size, font_family = userConfiguration(request)

    context = {
        'form': form,
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
    }
    return render(request, 'config.html', context)


def index(request):
    # Manejo de la sesion del usuario
    username, font_size, font_family = userConfiguration(request)

    # Odenar los comentario por tiempo
    order = 'desc'
    if request.method == 'POST':
        order = request.POST.get('order', 'desc')

    comments = ordenarCamarasFecha(order)

    # Crear el contexto
    context = {
        'comments': comments,
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
    }

    return render(request, 'index.html', context)


@never_cache
def camaras(request):
    # Obtener las fuentes de datos disponibles en static/xml
    random_img = None
    order = 'desc'
    if request.method == 'POST':
        xml_selected = request.POST.get(f'{"selected_xml"}')
        order = request.POST.get('order', 'desc')
        if xml_selected == "clean":
            limpiar_camaras()
        elif xml_selected is not None:
            print(f"XML seleccionado: {xml_selected}")
            cargar_camaras(xml_selected)
            get_img(xml_selected)

    cameras = ordenarCamarasComentarios(order)

    username, font_size, font_family = userConfiguration(request)

    random_img = get_imagen_aleatoria()
    xml_files = get_xml()

    context = {
        'request': request,
        'xml_files': xml_files,
        'random_img': random_img,
        'cameras': cameras,
        'cameras_count': cameras.count(),
        'comments_count': Comment.objects.count(),
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
    }
    return render(request, 'paginaCamaras.html', context)


def pag_camaras(request, id):
    # Seleccionar la cámara con el identificador indicado. Si no existe, se muestra un mensaje de error.

    # Obtener la cámara del id inidicado
    camera = Camera.objects.filter(id=id).first()

    if camera is None:
        return HttpResponse("Cámara no encontrada")

    # Ordenar los comentarios por tiempo
    order = 'desc'
    if request.method == 'POST':
        order = request.POST.get('order', 'desc')

    # Obtener todos los comentarios de la camera ordenados por fecha
    comments = ordenarComentariosFecha(
        Comment.objects.filter(camera=camera), order)

    # Obtener el nombre de usuario, tamaño de letra y estilo
    username, font_size, font_family = userConfiguration(request)

    context = {
        'request': request,
        'camera': camera,
        'comments': comments,
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
    }

    return render(request, 'camaras.html', context)


def guardar_comentario(request, camera, name):

    # Funcion para guardar un comentario si se ha hecho un post request

    comment_text = request.POST.get('body')
    if comment_text:  # Verificamos que el texto no es vacío
        # Guardar el comentario en la base de datos
        img_comment = guardar_comentarios(camera.img_path)
        comment = Comment(name=name, camera=camera, comment=comment_text,
                          date=timezone.now(), img_path_comment=img_comment)
        comment.save()


def ver_comentarios(request):
    camera_id = request.GET.get('camera_id')
    camera = Camera.objects.filter(id=camera_id).first()
    username, font_size, font_family = userConfiguration(request)

    if camera is None:
        return HttpResponse("Cámara no encontrada")

    if request.method == 'POST':
        guardar_comentario(request, camera, username)

    # Obtener todos los comentarios mas nuevos de la camara
    comments = Comment.objects.filter(camera=camera).order_by('-date')
    context = {
        'request': request,
        'comments': comments,
        'camera': camera,
        'now': timezone.now(),
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
    }
    return render(request, 'comentarios.html', context)


def camara_id(request, id):

    # Seleccionar la cámara con el identificador indicado. Si no existe, se mostrará un mensaje de error.

    camera = Camera.objects.filter(id=id).first()
    username, font_size, font_family = userConfiguration(request)

    if camera is None:
        return HttpResponse("Cámara no encontrada")

    camera.img_path = get_imagen_actual(id)
    print(f"Imagen actual: {camera.img_path}")

    if request.method == 'POST':
        guardar_comentarios(request, camera, username)

    # Obtener todos los comentarios de la camara
    comments = Comment.objects.filter(camera=camera).order_by('-date')
    context = {
        'request': request,
        'comments': comments,
        'camera': camera,
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
        'now': timezone.now(),
        'username': username,
        'font_size': font_size,
        'font_family': font_family,
    }
    return render(request, 'camara_id.html', context)


def get_url(img_path):

    # Obtiene la URL de la última imagen

    if img_path is None:
        print("No se encontró ninguna imagen")
        return None

    return img_path + '?t=' + str(time.time())


def get_imagen(request, id):

    #Obtener la imagen de la camara
    camera = Camera.objects.filter(id=id).first()
    if camera is None:
        return HttpResponse("Cámara no encontrada")

    img_path = get_imagen_actual(id)
    context = {
        'request': request,
        'camera': camera,
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
        'latest_image_url': get_url(img_path),
    }
    return render(request, 'imagen.html', context)


def cargar_comentarios(request, id):

    # Cargar los comentarios de las camaras
    camera = Camera.objects.filter(id=id).first()
    if camera is None:
        return HttpResponse("Cámara no encontrada")

    # Obtener todos los comentarios de la camara
    comments = Comment.objects.filter(camera=camera).order_by('-date')

    context = {
        'request': request,
        'comments': comments,
        'camera': camera,
        'now': timezone.now(),
        'cameras_count': Camera.objects.count(),
        'comments_count': Comment.objects.count(),
    }
    return render(request, 'cargar_comentarios.html', context)


def camara_json(request, id):
    try:
        cam = Camera.objects.get(id=id)
    except Camera.DoesNotExist:
        raise Http404("Cámara no disponible")

    # Obtener los comentarios de la camara
    comments = Comment.objects.filter(camera=cam)

    # Serializar los comentarios a JSON
    comments_json = serializers.serialize('json', comments)

    data = {
        'id': cam.id,
        'source_id': cam.source_id,
        'src': cam.src,
        'img_path': cam.img_path,
        'num_comments': comments.count(),
        'comments': comments_json,
    }
    return JsonResponse(data)


def camaras_json(request):
    cameras = Camera.objects.all()
    data = []
    for cam in cameras:
        # Obtener los comentarios de la camara
        comments = Comment.objects.filter(camera=cam)

        # Serializar los comentarios a JSON
        comments_json = serializers.serialize('json', comments)

        data.append({
            'id': cam.id,
            'source_id': cam.source_id,
            'src': cam.src,
            'img_path': cam.img_path,
            'num_comments': comments.count(),
            'comments': comments_json,
        })
    return JsonResponse(data, safe=False)


def help(request):
    username, font_size, font_family = userConfiguration(request)
    context = {
        'username': username,

TeVeO/TeVeOapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TeVeO</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <link rel="icon" type="image/ico" href="{% static 'img/icon/favicon.ico' %}">
    <!-- Iconos de la camara y de comentarios sib de Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body class="{{ font_size }} {{ font_family }}">
   <header id="header">
    <div class="header-container">
        <img src="{% static 'img/resources/header.jpg' %}" class="img-fluid header" alt="...">
        <div class="d-flex justify-content-between align-items-center">
            <a href="{% url 'index' %}" class="header-title" style="font-size: 70px; font-weight: bold;"> TeVeO </a>
            <span class="user-text font-weight: bold;">Nombre de usuario: {{ username }}</span>
        </div>
    </div>
</header>


    <nav id="navbar" class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a href="/">
          <img src="{% static 'img/icon/favicon.png' %}" alt="favicon" style="width: 50px; height: 50px;">
          </a>
          <a class="navbar-brand" href="{% url 'index' %}">TeVeO</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <!-- Esto es para ir a la pagina Principal -->
              {% if request.path != '/' %}
                  <li class="nav-item">
                    <a class="nav-link active text-nav-activated" aria-current="page" href="{% url 'index' %}" style="font-size: 18px; font-weight: bold;">Inicio</a>
                  </li>
              {% else %}
                  <li class="nav-item">
                    <a class="nav-link disabled text-nav-desactivated" aria-current="page">Principal</a>
                  </li>
              {% endif %}


              <!-- Esto es para el texto que te lleva a todas las camaras  -->
              {% if request.path != '/camaras/' %}
                <li class="nav-item">
                  <a class="nav-link active text-nav-activated" href="{% url 'mainCameras' %}" style="font-size: 18px; font-weight: bold;">Cámaras</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <span class="nav-link disabled text-nav-desactivated" aria-current="page">Cámaras</span>
                </li>
              {% endif %}

              {% if request.path != '/admin/' %}
                <li class="nav-item">
                   <a class="nav-link active text-nav-activated" href="{% url 'admin:index' %}" style="font-size: 18px; font-weight: bold;">Administración</a>
                </li>
              {% else %}
                <li class="nav-item">
                   <span class="nav-link disabled text-nav-desactivated" aria-current="page">Administración</span>
                </li>
              {% endif %}


              {% if request.path != '/config/' %}
                <li class="nav-item">
                  <a class="nav-link active text-nav-activated" href="{% url 'config' %}" style="font-size: 18px; font-weight: bold;">Configuración</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <span class="nav-link disabled text-nav-desactivated" aria-current="page">Configuración</span>
                </li>
              {% endif %}

              {% if request.path != '/ayuda/' %}
                <li class="nav-item">
                  <a class="nav-link active text-nav-activated" href="{% url 'ayuda' %}" style="font-size: 18px; font-weight: bold;">Ayuda</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <span class="nav-link disabled text-nav-desactivated" aria-current="page">Ayuda</span>
                </li>
              {% endif %}


            </ul>

          </div>
        </div>
    </nav>

    <main id="main-content">
        {% block body %}
        {% endblock %}
    </main>

    <div id="footer" class="container">
      <footer class="py-0.5 my-0 border-top fixed-bottom bg-white text-black">
        <div class="row">
          <div class="col d-flex justify-content-center align-items-center">
            <i class="fas fa-video fa-2x me-1"></i>
            <h5 class="mb-0">Cámaras: <span class="badge" style="background-color: #ffffff; color: #000000;">{{ cameras_count }}</span></h5>
          </div>
          <div class="col d-flex justify-content-center align-items-center">
            <i class="fas fa-comments fa-2x me-1"></i>
              <h5 class="mb-0">Comentarios: <span class="badge" style="background-color: #ffffff; color: #000000;">{{ comments_count }}</span></h5>
          </div>
        </div>
      </footer>
    </div>

    <div class="b-example-divider"></div>

</body>
</html>

TeVeO/TeVeOapp/templates/camara_id.html
{% extends 'base.html' %}
{% load static %}
<!-- index.html -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>


{% block body %}
<script src="https://unpkg.com/htmx.org@1.9.12"></script>
<div id="main-content" class="row">
    <div id="camera-details" class="col-6 text-center">
        <div class="text-black custom-gray-bg" style="border-radius: 10px; padding: 20px; margin-top: 20px; margin-right: 20px; margin-left: 20px;">
            <h1 style="margin-top: 20px;">{{ camera.name }}</h1>
            <p>Coordenadas: {{ camera.coordinates }}</p>
            <p>ID: {{ camera.id }}</p>
            <a href="{% url 'camera' camera.id %}" class="link">Ver cámara</a>
            <p>Hora actual: {{ now }}</p>
        </div>
        <img src="{% static camera.img_path %}" class="img_size_camera" alt="" hx-get="{% url 'latest_image' camera.id %}?{{now}}" hx-trigger="every 30s" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' hx-swap="outerHTML">
    </div>
    <div id="comment-section" class="col-6">
        <div class="text-black custom-gray-bg" style="border-radius: 10px; padding: 20px; margin-top: 20px; margin-right: 20px; margin-left: 20px;">
            <h1 style="margin-top: 20px; text-align: center;">Comentarios</h1>
        </div>
        <form id="comment-form" action="" method="POST" class="form-group row" style="margin-top: 20px; margin-right: 20px; margin-left: 20px;">
            {% csrf_token %}
            <div class="col-9">
                <label for="commentBody">Introduce un comentario:</label>
                <input type="text" id="commentBody" name="body" class="form-control" placeholder="Escribe tu comentario aquí...">
            </div>
            <div class="col-3 d-flex align-items-end">
                <button type="submit" class="btn mt-3 custom-gray-bg text-black">Enviar comentario</button>
            </div>
        </form>
        <div id="comment-list" hx-get="{% url 'get_comments' camera.id %}?{{now}}" hx-trigger="every 30s" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' hx-swap="outerHTML" hx-boost="true">
            {% include 'cargar_comentarios.html' %}
        </div>
    </div>
</div>

{% endblock %}

TeVeO/TeVeOapp/templates/cargar_comentarios.html
{% load static %}
{% load tz %}
{% now "U" as current_timestamp %}
<div id="comment-list" hx-get="{% url 'get_comments' camera.id %}?{{current_timestamp}}" hx-trigger="every 30s" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' hx-swap="outerHTML" hx-boost="true">
    {% if comments %}
    {% for comment in comments %}
        <div id="comment-{{ comment.id }}" class="text-black custom-gray-bg" style="border-radius: 10px; padding: 20px; margin-top: 20px;">
            <h5>{{ comment.name }}: {{ comment.comment }}</h5>
            <p><small>Fecha: {{ comment.date }}</small></p>
        </div>
    {% endfor %}
{% else %}
    <div id="no-comments" class="text-black custom-gray-bg" style="border-radius: 10px; padding: 20px; margin-top: 20px;">
        <h5>No hay comentarios para esta cámara por el momento.</h5>
    </div>
{% endif %}
</div>

TeVeO/TeVeOapp/templates/imagen.html
<!-- camera_image.html -->
{% load static %}
{% load tz %}
{% now "U" as current_timestamp %}
<img id="camera-image" src="{% static camera.img_path %}?{{current_timestamp}}" class="img_size_camera" alt="" hx-get="{% url 'latest_image' camera.id %}?{{current_timestamp}}" hx-trigger="every 30s" hx-swap="outerHTML">

TeVeO/TeVeOapp/templates/paginaCamaras.html
{% extends 'base.html' %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% block body %}
{% if xml_files %}
<div id="data-sources" class="container text-center">
    <div class="row tn-primary">
        <div id="camera-list" class="col-lg-6 order-lg-1 bg-custom-col-color text-gray-custom"> <!-- Cambiado a col-lg-6 -->
            <h2 class="mb-4 p-3 bg-dark text-white rounded mt-4">Lista de cámaras</h2>
            <div class="container text-center">
                <figure>
                    {%if random_img %}
                        <img src="{% static 'img/data/'|add:random_img %}" class="img-thumbnail" alt="" style="width: 300px; height: 200px;">
                        <figcaption class="text-white">Imagen aleatoria</figcaption>
                    {% else %}
                        <h2 class="mb-4 p-3 bg-danger rounded text-white">&#9888; Carga una fuente de datos  &#9888;</h2>
                    {% endif %}
                </figure>
                <hr>
                <div class="row">
                    {% if cameras %}
                        <div id="cameraCarousel" class="carousel slide" data-bs-ride="carousel">
                            <div class="carousel-inner">
                                {% for camera in cameras %}
                                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                        <div class="d-flex justify-content-center align-items-center">
                                            <img src="{% static camera.img_path %}" class="d-block w-100 img-fluid" alt="{{ camera.name }}" style="max-height: 300px;">
                                        </div>
                                        <div class="carousel-caption d-none d-md-block text-center">
                                            <h5 class="information">{{ camera.name }}</h5>
                                            <p class="information">ID: {{ camera.id }}</p>
                                            <div class="row">
                                                <a href="{% url 'camera' camera.id %}" class="information">Página de la cámara</a>
                                                <a href="{% url 'camera_dyn' camera.id %}" class="information">Página dinámica</a>
                                                <a href="{% url 'comment' %}?camera_id={{ camera.id }}" class="information">Página de comentarios</a>
                                                <a href="{% url 'camera_json' camera.id %}" class="information">JSON</a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <button class="carousel-control-prev" type="button" data-bs-target="#cameraCarousel" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#cameraCarousel" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                        <hr>
                    {% endif %}

                    <div class="container">
                        <h2 class="mb-4 p-3 bg-dark text-white rounded mt-4">Lista de cámaras</h2>
                        <form id="camera-order-form" method="post" style="margin-bottom: 2rem;"> <!-- Añadiendo margin-bottom -->
                            {% csrf_token %}
                            <div class="form-group row">
                                <label for="order" class="col-sm-4 col-form-label custom-label text-white">Ordenar cámaras:</label>
                                <div class="col-sm-6">
                                    <select class="form-control" id="order" name="order">
                                        <option value="desc">Cámaras más comentadas</option>
                                        <option value="asc">Cámaras menos comentadas</option>
                                    </select>
                                </div>
                                <div class="col-sm-2">
                                    <button type="submit" class="btn btn-dark">Ordenar</button>
                                </div>
                            </div>
                        </form>
                        <div class="row justify-content-center">
                            {% for camera in cameras %}
                            <div class="col-md-12">
                                <div class="card mb-3">
                                    <div class="row g-0">
                                        <div class="col-md-8 d-flex align-items-center rounded custom-gray-bg">
                                            <div class="card-body text-center text-black">
                                                <h5 class="card-title">{{ camera.name }}</h5>ID: {{ camera.id }} | Comentarios: {{ camera.comment_set.count }}</p>
                                                <div class="row">
                                                    <a href="{% url 'camera' camera.id %}" class="link">Página de la cámara</a>
                                                    <a href="{% url 'camera_dyn' camera.id %}" class="link">Página dinámica</a>
                                                    <a href="{% url 'comment' %}?camera_id={{ camera.id }}" class="link">Página de comentarios</a>
                                                    <a href="{% url 'camera_json' camera.id %}" class="link">JSON</a>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Imagen de la cámara -->
                                        <div class="col-md-4 d-flex align-items-center">
                                            <img src="{% static camera.img_path %}" class="card-img-bottom mx-auto d-block" alt="{{ camera.name }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                    <!-- Añadir un margen por abajo para que el pie no tape la última cámara de la lista -->
                    <div class="mb-5"></div>

                </div>
            </div>
        </div>
        <div id="data-source-list" class="col-lg-6 order-lg-2 bg-custom-col-color text-gray-custom text-white"> <!-- Cambiado a col-lg-6 -->
            <h2 class="mb-4 p-3 bg-dark text-white rounded mt-4">Fuentes de datos disponibles</h2>
            <form id="xml-selection-form" method="post">
                {% csrf_token %}
                {% for xml_file in xml_files %}
                    <div class="mb-2">
                        <span style="font-size: larger;" class="mt-4 text-white"> Fuente de datos: {{ xml_file }}</span><br>
                        <button type="submit" class="btn btn-dark" name="selected_xml" value="{{ xml_file }}">Cargar datos</button>
                    </div>
                    <hr>
                {% endfor %}
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-dark" name="selected_xml" value="clean">Eliminar datos (imágenes/comentarios)</button>
                </form>
                <a class="link" href="{% url 'cameras_json' %}">Cámaras en JSON</a>
            </form>
        </div>
    </div>
</div>

{% else %}
    <h1>¡No hay cámaras disponibles!</h1>
{% endif %}
{% endblock %}